const entrance=document.querySelector('#entrance'),main=document.querySelector('main');let openingTimer;
function openInvite(){startMusic();clearTimeout(openingTimer);entrance.classList.add('opening');main.inert=false;document.body.classList.remove('closed');openingTimer=setTimeout(()=>{entrance.hidden=true;},matchMedia('(prefers-reduced-motion: reduce)').matches?0:2300)}
document.querySelector('#open').addEventListener('click',openInvite);
document.querySelector('#replay').addEventListener('click',()=>{clearTimeout(openingTimer);window.scrollTo({top:0,behavior:'instant'});entrance.hidden=false;entrance.classList.remove('opening');document.body.classList.add('closed');main.inert=true;document.querySelector('#open').focus()});
const weddingDate=new Date('2027-03-03T18:00:00+05:30');function countdown(){let remaining=Math.max(0,Math.floor((weddingDate-Date.now())/1000));const values=[Math.floor(remaining/86400),Math.floor(remaining/3600)%24,Math.floor(remaining/60)%60,remaining%60];['days','hours','minutes','seconds'].forEach((id,i)=>document.getElementById(id).textContent=String(values[i]).padStart(2,'0'));if(!remaining)document.getElementById('count-label').textContent='Our wedding day has arrived'}countdown();setInterval(countdown,1000);
const canvas=document.querySelector('#scratch'),ctx=canvas.getContext('2d');let scratching=false,revealed=false,lastPoint=null,moves=0;function drawScratch(){if(revealed)return;const box=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=box.width*dpr;canvas.height=box.height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.globalCompositeOperation='source-over';const gradient=ctx.createLinearGradient(0,0,box.width,box.height);gradient.addColorStop(0,'#9b7139');gradient.addColorStop(.45,'#f0d39a');gradient.addColorStop(1,'#b88c46');ctx.fillStyle=gradient;ctx.fillRect(0,0,box.width,box.height);ctx.fillStyle='#48231d';ctx.textAlign='center';ctx.font='italic 23px Georgia';ctx.fillText('A date to remember',box.width/2,57);ctx.font='11px Arial';ctx.fillText('SCRATCH TO REVEAL',box.width/2,85)}
function reveal(){revealed=true;canvas.classList.add('revealed');document.querySelector('#reveal').textContent='03 March 2027 · Save the date';document.querySelector('#reveal').disabled=true}document.querySelector('#reveal').addEventListener('click',reveal);
function scratch(e){const r=canvas.getBoundingClientRect(),point={x:e.clientX-r.left,y:e.clientY-r.top};ctx.globalCompositeOperation='destination-out';ctx.lineWidth=38;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(lastPoint?.x??point.x,lastPoint?.y??point.y);ctx.lineTo(point.x,point.y);ctx.stroke();lastPoint=point;if(++moves%12===0){const p=ctx.getImageData(0,0,canvas.width,canvas.height).data;let erased=0,total=0;for(let i=3;i<p.length;i+=64){total++;if(p[i]<128)erased++}if(erased/total>.36)reveal()}}
canvas.addEventListener('pointerdown',e=>{scratching=true;lastPoint=null;canvas.setPointerCapture(e.pointerId);scratch(e)});canvas.addEventListener('pointermove',e=>{if(scratching&&!revealed)scratch(e)});['pointerup','pointercancel','lostpointercapture'].forEach(event=>canvas.addEventListener(event,()=>{scratching=false;lastPoint=null}));drawScratch();window.addEventListener('resize',drawScratch);
const events={pre:{title:'Nishant & Ankita — Haldi, Mehendi & Sangeet',start:'20270302T043000Z',description:'10:00 AM IST onwards. Join us for Haldi, Mehendi and Sangeet.'},wedding:{title:'Nishant & Ankita — Wedding Ceremony',start:'20270303T123000Z',description:'Wedding ceremony at 6:00 PM IST.'}};
function escapeICS(s){return s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
document.querySelectorAll('[data-calendar]').forEach(button=>button.addEventListener('click',()=>{const key=button.dataset.calendar,event=events[key],stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const text=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Explore Your Memories//Wedding Invitation//EN','CALSCALE:GREGORIAN','BEGIN:VEVENT',`UID:nishant-ankita-${key}-202703@eym-invitation`,`DTSTAMP:${stamp}`,`DTSTART:${event.start}`,`SUMMARY:${escapeICS(event.title)}`,`DESCRIPTION:${escapeICS(event.description)}`,`LOCATION:${escapeICS('Kishan Resort, Rukanpura, Patna, Bihar 800014')}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/calendar;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`Nishant-Ankita-${key}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}));

const weddingMusic=document.getElementById('wedding-music'),musicToggle=document.getElementById('music-toggle');weddingMusic.volume=.38;
function updateMusic(){const playing=!weddingMusic.paused;musicToggle.textContent=playing?'Music · On':'Music · Off';musicToggle.setAttribute('aria-pressed',String(playing));musicToggle.setAttribute('aria-label',playing?'Pause wedding music':'Play wedding music')}
function startMusic(){musicToggle.hidden=false;weddingMusic.play().then(updateMusic).catch(updateMusic)}
musicToggle.addEventListener('click',()=>{if(weddingMusic.paused){weddingMusic.play().then(updateMusic).catch(updateMusic)}else{weddingMusic.pause();updateMusic()}});
weddingMusic.addEventListener('pause',updateMusic);weddingMusic.addEventListener('play',updateMusic);
